name: Deploy Lovable via FTP na Hostinger

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 18 + cache
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Build do projeto
        env:
          CI: "true"
        run: npm run build

      - name: Verificar pasta de saída
        run: |
          if [ ! -d "dist" ] && [ ! -d "build" ]; then
            echo "Nenhuma pasta de build encontrada (dist/ ou build/)."
            exit 1
          fi
          echo "Conteúdo gerado:"
          ls -al dist || true
          ls -al build || true

      - name: Upload artefato (debug)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            dist/**
            build/**
          if-no-files-found: ignore

      - name: Deploy para Hostinger (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 21
          protocol: ftps
          # Se seu build gerar "build/" troque para build/
          local-dir: dist/
          # Pasta pública do subdomínio na Hostinger:
          server-dir: /domains/malta.ndossantosdias.com.br/public_html/
          dangerous-clean-slate: false
          dry-run: false
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/src/**
            **/README.md
